// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Asiento
{
    public int IdAsiento { get; set; }

    public int IdBus { get; set; }

    public int NumeroPiso { get; set; }

    public int NumeroAsiento { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public bool Estatus { get; set; }

    public virtual Bus IdBusNavigation { get; set; }
}