// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Bus
{
    public int IdBus { get; set; }

    public string NumeroPlaca { get; set; }

    public string Nombre { get; set; }

    public int CapacidadPiso1 { get; set; }

    public int CapacidadPiso2 { get; set; }

    public int? CapacidadTotal { get; set; }

    public bool Disponible { get; set; }

    public DateTime FechaCreacion { get; set; }

    public DateTime? FechaModificacion { get; set; }

    public int? UsuarioModificacion { get; set; }

    public bool Estatus { get; set; }

    public virtual ICollection<Asiento> Asientos { get; set; } = new List<Asiento>();

    public virtual ICollection<ConductorBu> ConductorBus { get; set; } = new List<ConductorBu>();

    public virtual ICollection<Viaje> Viajes { get; set; } = new List<Viaje>();
}