// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class ConductorBu
{
    public int ConductorBusId { get; set; }

    public int? ConductorId { get; set; }

    public int? BusId { get; set; }

    public DateOnly? FechaAsignacion { get; set; }

    public virtual Bus Bus { get; set; }

    public virtual Conductor Conductor { get; set; }
}