// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Reserva
{
    public int IdReserva { get; set; }

    public int? IdViaje { get; set; }

    public int? IdPasajero { get; set; }

    public int? AsientosReservados { get; set; }

    public decimal? MontoTotal { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual Viaje IdViajeNavigation { get; set; }

    public virtual ICollection<ReservaDetalle> ReservaDetalles { get; set; } = new List<ReservaDetalle>();
}