// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class ReservaDetalle
{
    public int IdReservaDetalle { get; set; }

    public int? IdReserva { get; set; }

    public int? IdAsiento { get; set; }

    public DateTime? FechaCreacion { get; set; }

    public virtual Reserva IdReservaNavigation { get; set; }
}