// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ConsoleApp1.Models;

public partial class Status
{
    public short StatusId { get; set; }

    public string Description { get; set; }
}